### ISSUE TITLE
unknown flag: --network

### ISSUE THREAD

**Issue by kenrtx** [acaloiaro/di-tui#26]
I have my key setup in the config and it works but whenever I try to use the network flag it says it is unknown.  

❯ ./go/bin/di-tui --network jazzradio
unknown flag: --network
Usage of ./go/bin/di-tui:
      --password string   your di.fm password
      --username string   your di.fm username
unknown flag: --network

All I have in my config is token and album art.  I'm curious what I might be doing wrong?

**Comment by acaloiaro** [comment]
Wow, thanks for catching this. Version `1.10.0` was waiting in Draft mode to be published as the latest release. 

When you upgrade to 1.10.0, you should be all set!

**Comment by kenrtx** [comment]
I am running into the same issue.  I installed it via go install and made sure I deleted it before reinstalling.  I can't tell what version it is though since there is no -v flag.  Am I typing it properly with `di-tui --network jazzradio`?

**Comment by acaloiaro** [comment]
Yeah sorry about the no `-v` flag. This project started as me building something for myself, and was surprised that people found and used it. 

With that said, head over to the releases (https://github.com/acaloiaro/di-tui/releases/tag/1.10.0) section and download the correct build for your platform. Whatever version you're currently running is not `1.10.0`. 

The command and args you provided above is correct for playing jazzradio.

**Comment by kenrtx** [comment]
It's a great client.  So much faster than the clunky web UI so thank you for sharing it!

 Still have the same issue.  I think the problem is the packages in the 1.10.0 release are from May 5th which seems to be 1.91 and the source is from 2 weeks ago which was 1.92.

**Comment by acaloiaro** [comment]
I just downloaded `di-tui_1.10.0_Linux_x86_64.tar.gz` from the releases page and it contains version 1.10.0, with the `--network` switch. 

Which package are you downloading?

**Comment by acaloiaro** [comment]
> But downloading the di-tui_1.10.0_Linux_x86_64.tar.gz seems to work. Not sure why the other methods didn't. Just happy it works now. 

Glad you got it working!

> It would be cool if you could play the playlists in addition to the stations. Guessing that is a limitation with DI?

Believe it or not, I'm not a DI expert. When you say playlists, do you mean the tracks that you see available for a station from the web UI? If so, that's an entirely different API that's rather thard to reverse engineer. I've done the work to reverse it, but the audio format it serves doesn't have any native Go decoders, so I opted not to incorporate it since one of this app's priorities is being go-native. We get away with that by using Pulseaduio and not importing any platform-specific audio software. 

The other reason `di-tui` is unlikely to support everything available in the web UI is because it's an undocumented API that can change at any time. Which is partially true of the one this app currently uses, but to a much lesser degree. Only login via username/password uses an undocumented API as of right now. We used to support adding/removing favorites through the undocumented API, but when they added Cloudflare in fron of it, it ended up blocking all of `di-tui`'s requests. 

I'll go ahead and close this issue for now. 

Cheers!
